import QRCode from 'qrcode';
import {initialBooking,selectionError,contactErrors,qrPayload} from './booking-model.js';
import {EVENT} from './event-config.js';
const escape=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function initBooking({navigate}){
 let state=initialBooking(),errors={},selection='',code='',qr='',generating=false;
 const container=document.querySelector('#reservation-content');
 function notice(){return '<p class="notice">Reserva de demostración. Esta confirmación no tiene validez de ingreso.</p>'}
 function form(){container.innerHTML=`<section class="reservation-card"><h1 tabindex="-1">Obtené tus entradas</h1><p>Tu entrada es gratuita. Reservá para vos y tu grupo.</p><div class="booking-event"><time datetime="${EVENT.date}">${EVENT.label}</time><span>${EVENT.access} · ${EVENT.venue}</span><p>Vení cuando quieras durante la jornada. No necesitás elegir un turno.</p></div>${notice()}<form id="booking-form" novalidate><div class="quantity-field"><div><p>Cantidad</p><small>Entre 1 y 6 entradas</small></div><div class="counter"><button type="button" data-quantity="-1" aria-label="Quitar una entrada" ${state.quantity===1?'disabled':''}>−</button><output id="booking-quantity" aria-live="polite">${state.quantity}</output><button type="button" data-quantity="1" aria-label="Agregar una entrada" ${state.quantity===6?'disabled':''}>+</button></div></div><p id="selection-error" class="field-error" role="alert">${selection}</p><fieldset><legend>Datos personales</legend><div class="field"><label for="guest-name">Nombre y apellido</label><input id="guest-name" name="name" autocomplete="name" value="${escape(state.name)}" required aria-invalid="${Boolean(errors.name)}" aria-describedby="name-error"><p id="name-error" class="field-error" role="alert">${errors.name||''}</p></div><div class="field"><label for="guest-email">Correo electrónico</label><input id="guest-email" name="email" type="email" autocomplete="email" value="${escape(state.email)}" required aria-invalid="${Boolean(errors.email)}" aria-describedby="email-error"><p id="email-error" class="field-error" role="alert">${errors.email||''}</p></div><div class="field"><label for="guest-accessibility">Necesidades de accesibilidad <span>(opcional)</span></label><textarea id="guest-accessibility" name="accessibility" aria-describedby="accessibility-hint">${escape(state.accessibility)}</textarea><p class="hint" id="accessibility-hint">Podés indicar qué necesitás para recorrer el evento.</p></div></fieldset><div class="booking-total"><span>${state.quantity} entrada${state.quantity>1?'s':''}</span><strong>Gratis</strong></div><div class="reservation-actions"><button type="button" class="button secondary" data-home>Volver</button><button type="submit" class="button">Continuar <span aria-hidden="true">↗</span></button></div></form></section>`}
 function summary(){container.innerHTML=`<section class="reservation-card"><h1 tabindex="-1">Verificá los datos</h1><p>Revisá tu selección antes de confirmar.</p>${notice()}<dl class="review-data"><div><dt>Día del evento</dt><dd>${EVENT.label}</dd></div><div><dt>Acceso</dt><dd>${EVENT.access}, sin turno</dd></div><div><dt>Sede</dt><dd>${EVENT.venue}</dd></div><div><dt>Cantidad</dt><dd>${state.quantity} entrada${state.quantity>1?'s':''}</dd></div><div><dt>Nombre</dt><dd>${escape(state.name)}</dd></div><div><dt>Correo electrónico</dt><dd>${escape(state.email)}</dd></div><div><dt>Accesibilidad</dt><dd>${escape(state.accessibility)||'Sin necesidades indicadas'}</dd></div><div><dt>Total</dt><dd>Gratis</dd></div></dl><div class="reservation-actions"><button class="button secondary" data-edit>Editar datos</button><button class="button" data-confirm>Confirmar</button></div></section>`}
 async function confirmation(){
  if(!code){code='FP-DEMO-'+crypto.randomUUID().slice(0,8).toUpperCase();qr=await QRCode.toDataURL(qrPayload(state,code),{width:600,margin:3,errorCorrectionLevel:'M',color:{dark:'#051014',light:'#fcfcfc'}})}
  if(location.hash!=='#confirmacion')return;
  container.innerHTML=`<section class="reservation-card confirmation"><h1 tabindex="-1">Tu confirmación está lista.</h1>${notice()}<p>${EVENT.label}<br>${EVENT.access} · ${EVENT.venue}<br>${state.quantity} entrada${state.quantity>1?'s':''} gratuita${state.quantity>1?'s':''}</p><img class="qr" src="${qr}" width="220" height="220" alt="Código QR de demostración sin validez de ingreso"><p class="ticket-code">${code}</p><p class="arrival">Vení en cualquier momento de la jornada. Presentás tu QR durante la acreditación y recibís tu pasaporte físico. Después, completás las tres estaciones en orden.</p><div class="reservation-actions"><a class="button" href="${qr}" download="${code}.png">Descargar QR <span aria-hidden="true">↓</span></a><button class="button secondary" data-reset>Volver</button></div></section>`;focusTitle();
 }
 function focusTitle(){container.querySelector('h1')?.focus({preventScroll:true})}
 function storeForm(){const form=container.querySelector('#booking-form');if(form){const data=new FormData(form);for(const key of ['name','email','accessibility'])state[key]=String(data.get(key)||'')}}
 function updateSelection(){container.querySelector('#booking-quantity').textContent=state.quantity;container.querySelector('.booking-total span').textContent=state.quantity+' entrada'+(state.quantity>1?'s':'');container.querySelector('[data-quantity="-1"]').disabled=state.quantity===1;container.querySelector('[data-quantity="1"]').disabled=state.quantity===6;selection=selectionError(state);container.querySelector('#selection-error').textContent=selection}
 const submit=event=>{if(event.target.id!=='booking-form')return;event.preventDefault();storeForm();selection=selectionError(state);errors=contactErrors(state);container.querySelector('#selection-error').textContent=selection;for(const key of ['name','email']){container.querySelector('#'+key+'-error').textContent=errors[key];container.querySelector('#guest-'+key).setAttribute('aria-invalid',String(Boolean(errors[key])))}if(selection){container.querySelector('[data-quantity="1"]')?.focus();return}if(errors.name||errors.email){container.querySelector('#guest-'+(errors.name?'name':'email')).focus();return}navigate('#revision')};
 const click=async event=>{const button=event.target.closest('button');if(!button)return;
  if(button.dataset.quantity){state.quantity=Math.max(1,Math.min(6,state.quantity+Number(button.dataset.quantity)));updateSelection()}
  else if(button.hasAttribute('data-home')){storeForm();navigate('#tickets')}
  else if(button.hasAttribute('data-edit'))navigate('#entradas');
  else if(button.hasAttribute('data-confirm')){if(generating)return;generating=true;button.disabled=true;button.textContent='Preparando QR…';navigate('#confirmacion');generating=false}
  else if(button.hasAttribute('data-download')){const a=document.createElement('a');a.href=qr;a.download=code+'.png';a.click()}
  else if(button.hasAttribute('data-reset')){state=initialBooking();errors={};selection='';code=qr='';navigate('#inicio')}
 };
 container.addEventListener('submit',submit);container.addEventListener('click',click);
 return {save:storeForm,show(hash){if(!['#entradas','#revision','#confirmacion'].includes(hash))return false;if(hash!=='#entradas'&&(selectionError(state)||Object.values(contactErrors(state)).some(Boolean))){navigate('#entradas');return true}if(hash==='#entradas')form();else if(hash==='#revision'){code=qr='';summary()}else{container.innerHTML='<section class="reservation-card"><h1 tabindex="-1">Preparando tu confirmación…</h1></section>';confirmation()}focusTitle();return true},dispose(){container.removeEventListener('submit',submit);container.removeEventListener('click',click)}};
}
